# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'Personal Cloud'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PurpleSandLProd'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'infrastructure.json'
    csmParametersFile: 'logic.json'
    deploymentMode: 'Incremental'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirector)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirector)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Personal Cloud'
    appType: 'webApp'
    WebAppName: 'PurpleSandL'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'