# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureFileCopy@3
  inputs:
    SourcePath: '.'
    azureSubscription: 'Visual Studio Professional(a7c01838-8c1a-463f-85db-9b46c88dd664)'
    Destination: 'AzureBlob'
    storage: 'psandlweb'
    ContainerName: '$web'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Published build with $(Build.SourceVersionMessage)"'