# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureFileCopy@3
  inputs:
    azureSubscription: 'Personal Cloud'
    Destination: 'AzureBlob'
    storage: 'psandlbootstrap'
    ContainerName: 'psandlbootstrap'

- task: AzureResourceGroupDeployment@2
  enabled: 'false'
  inputs:
    azureSubscription: 'Personal Cloud'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PurpleSandLProd'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'infrastructure.json'
    csmParametersFile: 'logic.json'
    deploymentMode: 'Incremental'

- task: AzureFileCopy@3
  inputs:
    azureSubscription: 'Personal Cloud'
    Destination: 'AzureVMs'
    storage: 'psandlbootstrap'
    resourceGroup: 'PURPLESANDLPROD'
    MachineNames: 'purpsandlweb'
    vmsAdminUserName: 'pbadmin'
    vmsAdminPassword: 'PB@dministratorPassword123'
    TargetPath: 'c:\\inetpub\\wwwroot\\'
    CleanTargetBeforeCopy: true