# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureResourceGroupDeployment@2
  enabled: 'false'
  inputs:
    azureSubscription: 'Personal Cloud'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PurpleSandLProd'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'infrastructure.json'
    csmParametersFile: 'logic.json'
    deploymentMode: 'Incremental'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'ls'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Personal Cloud'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp deployment source config-zip --resource-group PurpleSandLProd --name purplesandl --src $(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'